projects = [
    "SamuConceptCharacter",
    "SamuConceptIllustration",
    "Saint-John",
    "HomardRojas",
    "CarbonixWorkerSuit",
    "ClimbingExoSuit",
    "Intru",
    "UmbrellaKnight",
    "ClimbingExoSuit3d",
    "TeamBlue",
    "TribalYellowDemon",
    "UrbanWhiteCrowMan",
]