
[ports]
http = 7878
https =  3000

[interactive_name]
titles = ["Audrick Yeu", "Portofolio", "Concept Artist"]

# The order in wich the post are show in the masonry
[masonry]
projects = [
    "SamuConceptCharacter",
    "SamuConceptIllustration",
    "Saint-John",
    "HomardRojas",
    "CarbonixWorkerSuit",
    "ClimbingExoSuit",
    "Intru",
    "UmbrellaKnight",
    "ClimbingExoSuit3d",
    "TeamBlue",
    "TribalYellowDemon",
    "UrbanWhiteCrowMan",
]