# Experimental!

Path     ← "sessions.data"
Database ← &frab Path

# ---- Add UUID ----
□
□NaN
□°binaryDatabase
⊙⊙°□°⊟₃⇌⊟₃ # Adds a UUID with a Name to datbase
insert
# --- Remove UUID ---
# °binaryDatabase
# remove "5b580d2e-e38a-41de-a60b-7f5a2fd76686"
# --- Rename UUID ---
# °binaryDatabase
# □ "chandler"
# □ "sfafafvv-e383-dghdfbdba-4f5a2fd76686"
# insert

#map □"5b580d2e-e38a-41de-a60b-7f5a2fd76686" □"root"
?

binary
&fwa Path